"""
Script to fill a DuckDB database with files produced by some stations.
There is a folder for each station, containing all the files generated by that station.
A loop iterates through the stations, and for each one, it sorts the files by type 
and inserts them into the appropriate database tables. The file types for each station 
and the corresponding table are specified in the station configuration.

Here is an example of two different stations: one with a single vertical measurement level 
(and thus one instrument and one file per type) and one station with two vertical levels.
"""

import duckdb as db
import os
from src.utils import setup_logging
from src.db_tools import fill_db_station_toa5

# create a .log file with all the errors
setup_logging(__file__)

#################################################################
# --- CONFIG ---
from station_config import *

#################################################################
# --- FILL DB PIPELINE ---
print("Starting ETL Pipeline...")

# output database file
# the database file must contains the table wanted
database = ""
# root directory containing the subfolder of each stations
input_dir = ""

# the list of stations to fill the database with
stations = [s_4175, s_26458]

# loop over the station
with db.connect(database) as con:
    for station in stations:
        print(f"--- Processing Station {station.station_name} ---")

        # single station directory, here is the name of the station
        station_dir = os.path.join(input_dir, station.station_name+"_sd")

        # fill all the tables related to the station
        fill_db_station_toa5(con, station, station_dir)
print("Pipeline executed successfully.")


