"""
Must be executed after example_create_db.py

Script to fill a DuckDB database with files produced by some stations.
There is a folder for each station, containing all the files generated by that station.
A loop iterates through the stations, and for each one, it sorts the files by type 
and inserts them into the appropriate database tables. The file types for each station 
and the corresponding table are specified in the station configuration.

Here is an example of two different stations: one with a single vertical measurement level 
and thus one instrument and one file per type) and one station with two vertical levels.
"""

import duckdb as db
from pathlib import Path
from EddyCovTools.utils import setup_logging
from EddyCovTools.db_tools import fill_db_station_toa5
from .station_config import * # import station configuration

# create a .log file with all the errors
setup_logging(__file__)

#################################################################
# --- FILL DB PIPELINE ---
print("Starting ETL Pipeline...")

# output database file
# the database file must contains the table wanted
database = "./data/database.db"
# root directory containing the subfolder of each stations
input_dir = "./data"

# the list of stations to fill the database with
stations = [s_26458, s_4175]

# loop over the station
with db.connect(database) as con:
    for station in stations:
        station_id = station.station_name
        print(f"\n--- Processing Station {station_id} ---")

        # single station directory
        station_dir = Path(input_dir) / Path(f"station_{station_id}")

        # fill all the tables related to the station
        fill_db_station_toa5(con, station, station_dir)
print("Pipeline executed successfully.")


