import csv
import warnings
from typing import Tuple
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from collections import defaultdict
from .file_manager import toa5_to_df

def filter_df_toa5(df: pd.DataFrame) -> pd.DataFrame:
    """
    Replace numerical entries greater than 999 with NAN. 
    These values are generated by sonic anemometer Gill Windmaster when
    a measurment error occurs.

    Parameters
    ----------
    df: pd.DataFrame
        Pandas dataframe to filter
    
    Returns
    -------
    pd.DataFrame
        Pandas dataframe with entries > 999 replaced by NAN
    """
    # select the column of numbers
    numeric_cols = df.select_dtypes(include=['number']).columns
    # remove values == 999.99, generated by measurment errors
    # these values are replaced by NAN
    df[numeric_cols] = df[numeric_cols].mask(df[numeric_cols] > 999)
    return df

def check_TOA5 (input_dir : str,
                dt_max_ms : int,
                start_name : str,
                end_name : str,
                out_file : bool = False) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Check number of NAN in raw converted TOA5 file and time gaps between rows.
    Usefull to check the status of incoming file from Station direclty on the server.

    Parameters
    ----------
    input_dir: str
        path to directory containing all TOA5 from Stations.
    dt_max_ms: int
        max time gaps between consequent rows in milliseconds.
    start_name: str
        beginning of filename to analyze, to select files from folder.
    end_name: str
        ending of filename to analyze, to select files from folder.
    out_file: bool
        create CSV file with NAN rows and time gaps info. Defaulf False.

    Returns
    -------
    Tuple[pd.DataFrame, pd.DataFrame]
        - First pandas Dataframe with all the time gaps found into the file.
        - Second pandas Dataframe with all rows containing at least one NAN record.
    """

    # list of dataframe
    df_gaps_list = []
    df_nan_list = []

    # get all file order by AZ
    files = sorted([f for f in os.listdir(input_dir) if f.startswith(start_name) and f.endswith(end_name)])
    print(f"Find {len(files)} file")

    # last row from previous file
    last_row_prev_file = None
    last_file = None

    for file in files:
        filepath = os.path.join(input_dir, file)

        try:
            df, meta = toa5_to_df(input_file=filepath)

            if df.empty:
                print(f"Analyzing: {file}")
                print(f"Empty file, skipping\n")
                continue
            
            # Comparison between last timestamo in previous file and first timestamp of current file
            if last_row_prev_file is not None:
                ts_prev = last_row_prev_file.index[0]
                ts_first = df.index[0]
                
                if pd.notna(ts_prev) and pd.notna(ts_first):
                    dt_ms = (ts_first - ts_prev).total_seconds() * 1000
                    if dt_ms > dt_max_ms:
                        print(f"Analyzing: {file}")
                        print(f"  ⚠️ Time gap between {last_file} and {file}: dt = {dt_ms/1000:.2f} s")
                        row = pd.DataFrame({
                            "file": [f"{last_file} → {file}"],
                            "dtSec": [dt_ms / 1000]
                        })
                        df_gaps_list.append(row)
                else:
                    print(f"Analyzing: {file}")
                    print("  ⚠️ Missing timestamp between consecutive files")
            
            # Calc dt in milliseconds between rows in file
            delta_t = df.index.diff().total_seconds() * 1000
            
            # Find index with dt > threshold
            time_gaps_index = delta_t[delta_t > dt_max_ms]

            # Append rows with time gaps
            if len(time_gaps_index) > 0:
                row_with_gaps = pd.DataFrame({
                            "file": [file],
                            "dtSec": delta_t[delta_t > dt_max_ms].to_numpy()/1000,
                            "TIMESTAMP": df.index[delta_t > dt_max_ms]
                        })
                df_gaps_list.append(row_with_gaps)
                print(f"Analyzing: {file}")
                print(f"  ✓ Find {len(row_with_gaps)} rows with delta t > {dt_max_ms} ms")
            
            # Find rows with at least one NAN
            nan_df = df[df.eq('NAN').any(axis=1)]
            if len(nan_df) > 0:
                df_nan_list.append(nan_df)

            # Update values for next comparison between consecutive files
            last_row_prev_file = df.iloc[[-1]]
            last_file = file

        except Exception as e:
            print(f"Analyzing: {file}")
            print(f"  ✗ Error: {e}")

    info = meta[0].strip().split('","')
    # Build df
    if df_gaps_list:
        df_gaps = pd.concat(df_gaps_list, ignore_index=True)
        print(f"\n{'='*60}")
        print(f"TOTAL: {len(df_gaps)} rows with delta t > {dt_max_ms} ms (include gaps between files)")
        print(f"{'='*60}\n")
        print(df_gaps)
        if out_file:
            out_path = os.path.join(input_dir, f'time_gaps_{info[1]}_{info[7][:-1]}.csv')
            df_gaps.to_csv(out_path, index=False)
    else:
        print(f"\n{'='*60}")
        print("No time gaps found.")
        print(f"{'='*60}\n")
        df_gaps = pd.DataFrame()

    if df_nan_list:
        df_nan = pd.concat(df_nan_list, ignore_index=True)
        print("\n" + "="*60)
        print(f"TOTAL: {len(df_nan)} rows with NAN values")
        print("="*60 + "\n")
        print(df_nan)
        if out_file:
            out_path = os.path.join(input_dir, f'nan_{info[1]}_{info[7][:-1]}.csv')
            df_nan.to_csv(out_path, index=False)
    else:
        print(f"\n{'='*60}")
        print("No NAN values found")
        print(f"{'='*60}\n")
        df_nan = pd.DataFrame()

    return df_gaps, df_nan

def daily_file_from_server(input_dir: str, 
                          output_dir: str,
                          start_name : str,
                          end_name : str):
    """
    From fiel with DATETIME in the name
    Raggruppa i file TOA5 orari per giorno e tipologia (Slow/Sonic) 
    e li concatena in file giornalieri.
    """
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Dizionario per raggruppare i file. Formato: {('Slow', '2026-03-26'): [lista_file]}
    file_groups = defaultdict(list)

    # 1. Scansiona e raggruppa i file
    for file_path in input_path.glob(f'{start_name}*{end_name}'):
        nome_file = file_path.name
        parti = nome_file.split('_')
        
        # Ci aspettiamo nomi come: TOA5_Slow_2026-03-26_00-01-06.dat
        if len(parti) >= 4:
            tipo_file = parti[1]          # 'Slow' o 'Sonic'
            data_file = parti[2]          # '2026-03-26'
            
            file_groups[(tipo_file, data_file)].append(file_path)

    # 2. Concatena i file raggruppati
    for (tipo_file, data_file), files in file_groups.items():
        # Ordina i file alfabeticamente (che corrisponde all'ordine cronologico grazie ai nomi)
        files.sort()
        
        nome_output = f"TOA5_{tipo_file}_{data_file}_Daily.dat"
        output_file_path = output_path / nome_output
        
        print(f"Creazione di {nome_output} (unendo {len(files)} file)...")
        
        with open(output_file_path, 'w', encoding='utf-8') as outfile:
            for indice, file_orario in enumerate(files):
                with open(file_orario, 'r', encoding='utf-8') as infile:
                    # Se è il primo file, scrivi tutto (incluso l'header di 4 righe)
                    if indice == 0:
                        outfile.write(infile.read())
                    # Per i file successivi, salta le prime 4 righe
                    else:
                        for _ in range(4):
                            next(infile, None)  # Salta la riga
                        # Scrivi il resto dei dati
                        for riga in infile:
                            outfile.write(riga)

    print("Concatenazione completata!")

# Esempio di utilizzo:
# crea_file_giornalieri('./cartella_dati_orari', './cartella_dati_giornalieri')

import os
from pathlib import Path
from collections import defaultdict

def smista_e_unisci_sonic_per_contenuto(input_dir: str, output_dir: str):
    """
    Legge il timestamp reale all'interno dei file Sonic, li raggruppa per giorno 
    e crea i file giornalieri unificati.
    """
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Dizionario per raggruppare i file per data reale: {'2026-03-25': [lista_file]}
    file_per_data = defaultdict(list)
    
    print("Fase 1: Lettura del contenuto dei file per estrarre la data esatta...")
    
    # Trova tutti i file nella cartella (puoi filtrare per 'Sonic' se necessario)
    for file_path in input_path.glob('*.dat'):
        # Assicuriamoci che sia un file Sonic guardando la prima riga se vogliamo essere pignoli, 
        # oppure diamo per scontato che gli passi la cartella giusta.
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                # Salta le 4 righe di intestazione
                for _ in range(4):
                    f.readline()
                
                # Leggi la prima riga di dati veri
                prima_riga_dati = f.readline()
                
                if not prima_riga_dati:
                    continue # File vuoto, saltalo
                
                # La riga è tipo: "2026-03-25 23:00:00.05",21451954,4.595,...
                # Dividiamo per virgola, prendiamo il primo elemento, togliamo le virgolette
                timestamp_str = prima_riga_dati.split(',')[0].replace('"', '')
                
                # Ora abbiamo "2026-03-25 23:00:00.05". Prendiamo solo la data (prima dello spazio)
                data_reale = timestamp_str.split(' ')[0] 
                
                file_per_data[data_reale].append(file_path)
                
        except Exception as e:
            print(f"Errore nella lettura di {file_path.name}: {e}")

    print(f"Trovati dati per {len(file_per_data)} giorni diversi. Inizio unione...")

    # Fase 2: Unione dei file giornalieri (identica a prima, ma ora basata sulla data certa)
    for data_reale, files in file_per_data.items():
        # Ordiniamo i file: essendo basati sul timestamp orario, ordinarli alfabeticamente 
        # per nome (che contiene l'ora) di solito basta per metterli in ordine cronologico.
        files.sort()
        
        nome_output = f"TOA5_Sonic_{data_reale}_Daily.dat"
        output_file_path = output_path / nome_output
        
        print(f"-> Creazione di {nome_output} ({len(files)} file orari uniti)")
        
        with open(output_file_path, 'w', encoding='utf-8') as outfile:
            for indice, file_orario in enumerate(files):
                with open(file_orario, 'r', encoding='utf-8') as infile:
                    if indice == 0:
                        # Primo file del giorno: scrivi tutto, compreso l'header TOA5
                        outfile.write(infile.read())
                    else:
                        # File successivi: salta le 4 righe di header e copia i dati
                        for _ in range(4):
                            next(infile, None)
                        for riga in infile:
                            outfile.write(riga)

    print("Completato con successo!")

# Esempio di utilizzo:
# smista_e_unisci_sonic_per_contenuto('./dati_orari', './dati_giornalieri_sicuri')

def despiking_series_robust(input_series: pd.Series, 
                            robust_std_dev: float, 
                            n_window_points: int, 
                            show_plot: bool = False) -> Tuple[pd.Series, int]:
    """
    Applies a moving-window robust despiking algorithm directly to a pandas Series.
    If a record exceeds N times the robust standard deviation, it's marked as spike.
    
    Detected spikes are replaced with the local running median. 

    Parameters
    ----------
    input_series : pd.Series
        Input time series data with a DatetimeIndex.
    robust_std_dev : float
        Threshold multiplier for the robust standard deviation.
    n_window_points : int
        Number of periods for the rolling window.
    show_plot : bool, optional
        If True, displays a plot showing the original series, the dynamic bounds, 
        and the identified spikes. Default is False.

    Returns
    -------
    pd.Series
        The despiked series.
    int
        The number of spikes removed.
    """
    # check
    if not isinstance(input_series, pd.Series):
        raise TypeError("Input must be a pandas Series.")
    if robust_std_dev <= 0:
        raise ValueError("Number of standard dev must be a positive number.")
    if not isinstance(n_window_points, int) or n_window_points <= 0:
        raise ValueError("Window_length must be a positive integer.")
    if n_window_points % 2 == 0:
        warnings.warn("It is recommended to use odd number of point in window.")

    timeseries = input_series.copy()

    # --- Rolling Statistics using Pandas ---
    roll = timeseries.rolling(window=n_window_points, center=True, min_periods=1)
    
    running_median = roll.median()
    p84 = roll.quantile(0.84)
    p16 = roll.quantile(0.16)
    
    # definition of robust standard deviation
    running_std_robust = 0.5 * (p84 - p16)

    # --- Spike Detection and Replacement ---
    delta = np.maximum(robust_std_dev * running_std_robust, 0.5)

    upper_bound = running_median + delta
    lower_bound = running_median - delta

    # Create boolean mask for spikes 
    spike_mask = (timeseries > upper_bound) | (timeseries < lower_bound)
    count_spike = int(spike_mask.sum())

    # Visualize spikes and temporal series
    if show_plot:
        plt.figure(figsize=(14, 6))
        
        # input series in grey
        plt.plot(input_series.index, input_series, label='Input series', color='gray', alpha=0.5, linewidth=1)
        
        # tolerance band
        plt.fill_between(input_series.index, lower_bound, upper_bound, color='blue', alpha=0.1, label='Tolerance band')
        
        # despiked series in blue
        plt.plot(timeseries.index, timeseries.where(~spike_mask, running_median), label='Despiked series', color='blue', linewidth=1.5)
        
        # spikes red dot
        spikes_only = input_series[spike_mask]
        plt.scatter(spikes_only.index, spikes_only, color='red', label='Spike value', zorder=5, s=20)
        
        plt.title(f'Robust despike (Spike removed: {count_spike})', fontsize=14)
        plt.xlabel('Timestamp', fontsize=12)
        plt.ylabel('Value', fontsize=12)
        plt.legend(loc='best')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.tight_layout()
        plt.show()

    # Replace bad data with the local median using .loc
    timeseries.loc[spike_mask] = running_median.loc[spike_mask]

    return timeseries, count_spike

def despiking_TOA5_robust(file_path: str,
                          out_path: str, 
                          robust_std_dev: float, 
                          n_window_points: int, 
                          show_plot: bool = False) -> str:
    """
    Despike data directly from a TOA5 format file.
    Put despiked data into a similar TOA5 format: the first header row info is manteined.
    Info on the measurmemts units is lost in the new header.
    Applies a moving-window robust despiking algorithm.
    If a record exceeds N times the robust standard deviation, it's marked as spike.
    
    Detected spikes are replaced with the local running median. 

    Parameters
    ----------
    file_path : str
        Path to TOA5 data file from campbell datalogger
    out_path : str
        Output dir where put despiked file
    robust_std_dev : float
        Threshold multiplier for the robust standard deviation.
    n_window_points : int
        Number of periods for the rolling window.
    show_plot : bool, optional
        If True, displays a plot showing the original series, the dynamic bounds, 
        and the identified spikes. Default is False.

    Returns
    -------
    pd.Series
        The despiked series.
    int
        The number of spikes removed.
    """
    #import file
    df, meta = import_file(file_path)

    print(f"Despiking {file_path}")

    # select relevant column and mask row with error (from Gill Windmaster instrument) 
    columns_meas = ['u_1', 'v_1', 'w_1', 'Ts_1']
    condition = (df['SS_1'] != "0B") & (df['SS_1'] != "00") 
    df[columns_meas] = df[columns_meas].mask(condition)

    # despiking on measurments column
    for c in columns_meas:
        despiked_series, n_spikes = despiking_series_robust(
            df[c], 
            robust_std_dev=robust_std_dev, 
            n_window_points=n_window_points, 
            show_plot=show_plot
        )
        
        # replace column with despiked column
        df[c] = despiked_series
        
        print(f"Column {c}: {n_spikes} spike replaced.")

    #output file info
    print(f"Number of records in output file: {len(df)}.")
    print(f"First timestamp: {df.index.min()}")
    print(f"Lasr timestamp: {df.index.max()}")

    # output path
    in_path = Path(file_path)
    out_path = Path(out_path)
    # new filename
    out_path = out_path / f"desp_{in_path.stem}{in_path.suffix}"

    # Save to file header info and data despiked
    with open(out_path, 'w', encoding='utf-8') as f:
        f.writelines(meta[0])

    df.to_csv(out_path, mode='a', sep=",")

    return str(out_path)

def average_toa5(input_file, output_file, freq='10min'):
    """
    Reads a Campbell Scientific TOA5 file, averages the data based on a defined 
    time interval (freq), and exports it matching the original file structure.
    
    :param input_file: str, path to the input TOA5 file
    :param output_file: str, path for the output TOA5 file
    :param freq: str, pandas time frequency string (e.g., '1min', '30S', '1H')
    """
    #read the 4-line TOA5 header
    with open(input_file, 'r') as f:
        headers = [next(f) for _ in range(4)]
        
    #extract column names from the 2nd header line
    col_names = next(csv.reader([headers[1]]))

    #read data skipping the 4 header lines
    df = pd.read_csv(input_file, skiprows=4, header=None, names=col_names, na_values=["NAN", "INF"])

    #setup datetime index
    df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
    df.set_index('TIMESTAMP', inplace=True)

    # Use 'mean' for numeric data (u, v, T, RH) and 'first' for strings/flags (like "00" in SS_1)
    agg_rules = {}
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            agg_rules[col] = 'mean'
        else:
            agg_rules[col] = 'first'

    #resample and aggregate
    df_avg = df.resample(freq).agg(agg_rules)

    # (Optional) Rebuild the RECORD column as a clean sequential integer series
    if 'RECORD' in df_avg.columns:
        df_avg['RECORD'] = range(len(df_avg))

    # 6. Write output preserving TOA5 exact structure
    with open(output_file, 'w', newline='') as f:
        for line in headers:
            f.write(line)

    # Append data. QUOTE_NONNUMERIC ensures TIMESTAMP and strings (e.g. "00") are quoted,
    # while numbers remain unquoted, perfectly matching the TOA5 standard.
    df_avg.to_csv(output_file, mode='a', header=False, index=True, 
                  date_format='%Y-%m-%d %H:%M:%S', 
                  quoting=csv.QUOTE_NONNUMERIC)

# --- EXAMPLE USAGE ---
# average_toa5('slow_data.dat', 'slow_data_avg.dat', freq='1min')
# average_toa5('fast_data.dat', 'fast_data_avg.dat', freq='10min')