import csv
import warnings
from typing import Tuple
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from .file_manager import toa5_to_df, get_files_pattern
from .config import InputFileConfig

import logging
logger = logging.getLogger(__name__)

def filter_df_toa5(df: pd.DataFrame) -> pd.DataFrame:
    """
    Replace numerical entries greater than 999 with NAN. 
    These values are generated by sonic anemometer Gill Windmaster when
    a measurment error occurs.

    Parameters
    ----------
    df: pd.DataFrame
        Pandas dataframe to filter
    
    Returns
    -------
    pd.DataFrame
        Pandas dataframe with entries > 999 replaced by NAN
    """
    # select the column of numbers
    numeric_cols = df.select_dtypes(include=['number']).columns
    # remove values == 999.99, generated by measurment errors
    # these values are replaced by NAN
    df[numeric_cols] = df[numeric_cols].mask(df[numeric_cols] > 999)
    return df

def check_df(df: pd.DataFrame,
             sampling_rate_ms: float) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Find the time gaps in the dataframe index. The index must be a timestamp.
    Find the rows with at least one NAN values.
    Find the time duration of interval with consecutive NAN values.

    Parameters
    ----------
    df: pd.DataFrame
        Pandas dataframe to check
    sampling_rate_ms: float
        Expected dt in milliseconds between measure
    
    Returns
    -------
    Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]
        - First Pandas df with the time gaps in seconds between records,
          greater than sampling rate
        - Second Pandas df with rows containing at least one NAN record.
        - Third Pandas df with info about interval of consecutive NAN values.
          Contains the start and end times of the intervals and the number
          of consecutive NAN measures.
    """
    if not df.empty:
        # Calc dt in milliseconds between rows in file
        delta_t = df.index.diff().total_seconds() * 1000

        # Append rows with time gaps to a list
        row_with_gaps = pd.DataFrame({
            "TIMESTAMP": df.index[delta_t > sampling_rate_ms],
            "dtSec": delta_t[delta_t > sampling_rate_ms].to_numpy()/1000
        })
            
        # Find rows with at least one NAN
        nan_df = df[df.isna().any(axis=1)]

        # Find the duration of intervals with consecutive NANs
        dt = pd.to_timedelta(sampling_rate_ms, unit='ms')
        time_diff = nan_df.index.to_series().diff()
        is_new_block = time_diff != dt
        block_id = is_new_block.cumsum()
        duration_nan = df.groupby(block_id).apply(
            lambda x: pd.Series({
                'start': x.index[0],
                'end': x.index[-1],
                'n_sample': len(x),
            })
        )
        
        return row_with_gaps, nan_df, duration_nan

    else:
        logger.error("Empty dataframe.")
        return pd.DataFrame(), pd.DataFrame()

def despiking_series_robust(input_series: pd.Series, 
                            robust_std_dev: float, 
                            n_window_points: int, 
                            show_plot: bool = False) -> Tuple[pd.Series, int]:
    """
    Applies a moving-window robust despiking algorithm directly to a pandas Series.
    If a record exceeds N times the robust standard deviation, it's marked as spike.
    
    Detected spikes are replaced with NaN. 

    Parameters
    ----------
    input_series : pd.Series
        Input time series data with a DatetimeIndex.
    robust_std_dev : float
        Threshold multiplier for the robust standard deviation.
    n_window_points : int
        Number of periods for the rolling window.
    show_plot : bool, optional
        If True, displays a plot showing the original series, the dynamic bounds, 
        and the identified spikes. Default is False.

    Returns
    -------
    pd.Series
        The despiked series.
    int
        The number of spikes removed.
    """
    # check
    if not isinstance(input_series, pd.Series):
        raise TypeError("Input must be a pandas Series.")
    if robust_std_dev <= 0:
        raise ValueError("Number of standard dev must be a positive number.")
    if not isinstance(n_window_points, int) or n_window_points <= 0:
        raise ValueError("Window_length must be a positive integer.")
    if n_window_points % 2 == 0:
        warnings.warn("It is recommended to use odd number of point in window.")

    timeseries = input_series.copy()

    # --- Rolling Statistics using Pandas ---
    roll = timeseries.rolling(window=n_window_points, center=True, min_periods=1)
    
    running_median = roll.median()
    p84 = roll.quantile(0.84)
    p16 = roll.quantile(0.16)
    
    # definition of robust standard deviation
    running_std_robust = 0.5 * (p84 - p16)

    # --- Spike Detection and Replacement ---
    delta = np.maximum(robust_std_dev * running_std_robust, 0.5)

    upper_bound = running_median + delta
    lower_bound = running_median - delta

    # Create boolean mask for spikes 
    spike_mask = (timeseries > upper_bound) | (timeseries < lower_bound)
    count_spike = int(spike_mask.sum())

    # Visualize spikes and temporal series
    if show_plot:
        plt.figure(figsize=(14, 6))
        
        # input series in grey
        plt.plot(input_series.index, input_series, label='Input series', color='gray', alpha=0.5, linewidth=1)
        
        # tolerance band
        plt.fill_between(input_series.index, lower_bound, upper_bound, color='blue', alpha=0.1, label='Tolerance band')
        
        # despiked series in blue
        plt.plot(timeseries.index, timeseries.where(~spike_mask, running_median), label='Despiked series', color='blue', linewidth=1.5)
        
        # spikes red dot
        spikes_only = input_series[spike_mask]
        plt.scatter(spikes_only.index, spikes_only, color='red', label='Spike value', zorder=5, s=20)
        
        plt.title(f'Robust despike (Spike removed: {count_spike})', fontsize=14)
        plt.xlabel('Timestamp', fontsize=12)
        plt.ylabel('Value', fontsize=12)
        plt.legend(loc='best')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.tight_layout()
        plt.show()

    # Replace bad data with the local median using .loc
    #timeseries.loc[spike_mask] = running_median.loc[spike_mask]

    timeseries.loc[spike_mask] = np.nan

    return timeseries, count_spike

def interpolate_lin(df: pd.DataFrame,
                    limit: int) -> pd.DataFrame:
    """
    Linear interpolation on all df column.
    Only fill NaNs surrounded by valid values (interpolate).
    Limit set the maximum number of values to add during interpolation.
    If there is 20 consecutive NaN and limit = 4, only 8 values are added,
    4 starting from the far right of the range and 4 starting from the far left.

    Parameters
    ----------
    df: dp.Dataframe
        dataframe to interpolate
    limit: int
        Maximum number of consecutive NaNs to fill. Must be greater than 0.
    """
    df = df.interpolate(method='linear', limit=limit, limit_area='inside', limit_direction='both')
    return df

def interpolate_3pol(df: pd.DataFrame,
                     limit: int) -> pd.DataFrame:
    """
    Interpolate all df column with third-degree polynomial.
    Both interpolation and extrapolation are performed.
    Limit set the maximum number of values to add during interpolation.
    If there is 20 consecutive NaN and limit = 4, only 8 values are added,
    4 starting from the far right of the range and 4 starting from the far left.

    Parameters
    ----------
    df: dp.Dataframe
        dataframe to interpolate
    limit: int
        Maximum number of consecutive NaNs to fill. Must be greater than 0.
    """
    df = df.interpolate(method='spline', order=3, limit=limit, limit_direction='both')
    return df

'''def fill_mean(df: pd.DataFrame) -> pd.DataFrame:
    """
    Fill NaN with the mean of the entire column
    
    """
    df = df.fillna(df.mean())
    return df'''

'''def average_toa5(input_file, output_file, freq='10min'):
    """
    Reads a Campbell Scientific TOA5 file, averages the data based on a defined 
    time interval (freq), and exports it matching the original file structure.
    
    :param input_file: str, path to the input TOA5 file
    :param output_file: str, path for the output TOA5 file
    :param freq: str, pandas time frequency string (e.g., '1min', '30S', '1H')
    """
    #read the 4-line TOA5 header
    with open(input_file, 'r') as f:
        headers = [next(f) for _ in range(4)]
        
    #extract column names from the 2nd header line
    col_names = next(csv.reader([headers[1]]))

    #read data skipping the 4 header lines
    df = pd.read_csv(input_file, skiprows=4, header=None, names=col_names, na_values=["NAN", "INF"])

    #setup datetime index
    df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
    df.set_index('TIMESTAMP', inplace=True)

    # Use 'mean' for numeric data (u, v, T, RH) and 'first' for strings/flags (like "00" in SS_1)
    agg_rules = {}
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            agg_rules[col] = 'mean'
        else:
            agg_rules[col] = 'first'

    #resample and aggregate
    df_avg = df.resample(freq).agg(agg_rules)

    # (Optional) Rebuild the RECORD column as a clean sequential integer series
    if 'RECORD' in df_avg.columns:
        df_avg['RECORD'] = range(len(df_avg))

    # 6. Write output preserving TOA5 exact structure
    with open(output_file, 'w', newline='') as f:
        for line in headers:
            f.write(line)

    # Append data. QUOTE_NONNUMERIC ensures TIMESTAMP and strings (e.g. "00") are quoted,
    # while numbers remain unquoted, perfectly matching the TOA5 standard.
    df_avg.to_csv(output_file, mode='a', header=False, index=True, 
                  date_format='%Y-%m-%d %H:%M:%S', 
                  quoting=csv.QUOTE_NONNUMERIC)'''

def check_TOA5(input_dir : str | Path,
               pattern: str,
               config: InputFileConfig,
               out_file : bool = False) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Check number of NAN in raw converted TOA5 file and time gaps between rows.
    Usefull to check the status of incoming file from Station direclty on the server.

    Parameters
    ----------
    input_dir: str
        path to directory containing all TOA5 from Stations.
    pattern: str
        Wildcard pattern name of the files (e.g. S*.dat)
    config: InputFileConfig
        Object with all the info about the columns to be imported.
        Contains the correct sampling rate for this type of files.
    out_file: bool
        create CSV file with NAN rows and time gaps info. Defaulf False.

    Returns
    -------
    Tuple[pd.DataFrame, pd.DataFrame]
        - First pandas Dataframe with all the time gaps found into the file.
        - Second pandas Dataframe with all rows containing at least one NAN record.
    """
    # list of dataframe
    df_gaps_list = []
    df_nan_list = []

    # get all file order by AZ
    files = get_files_pattern(input_dir, pattern)

    # get dt for this type of files
    sampling_rate = config.sampling_rate_ms

    # last row from previous file
    last_row_prev_file = None
    last_file = None

    for file in files:
        try:
            df, meta = toa5_to_df(input_file=file, config=config, date_index=True)

            if df.empty:
                logger.error(f"Analyzing {file.name}: empty file, skipping...")
                continue
            
            # Comparison between last timestamp in previous file and first timestamp of current file
            if last_row_prev_file is not None:
                ts_prev = last_row_prev_file.index[0]
                ts_first = df.index[0]

                # calc delta t
                if pd.notna(ts_prev) and pd.notna(ts_first):
                    dt_ms = (ts_first - ts_prev).total_seconds() * 1000 #dt in ms between files
                    if dt_ms > sampling_rate: # gap found
                        logger.info(f"Time gap found between {last_file.name} and {file.name}: dt = {dt_ms/1000:.2f} s")
                        #append gap info to a list
                        row = pd.DataFrame({
                            "file": [f"{last_file.name} → {file.name}"],
                            "dtSec": [dt_ms / 1000]
                        })
                        df_gaps_list.append(row)
                else:
                    logger.error(f"Analyzing {file.name}: Missing timestamp between consecutive files")
            
            # Calc dt in milliseconds between rows in file
            delta_t = df.index.diff().total_seconds() * 1000
            
            # Find index with dt > threshold
            time_gaps_index = delta_t[delta_t > sampling_rate]

            # Append rows with time gaps to a list
            if len(time_gaps_index) > 0:
                row_with_gaps = pd.DataFrame({
                            "file": [file.name],
                            "dtSec": delta_t[delta_t > sampling_rate].to_numpy()/1000,
                            "TIMESTAMP": df.index[delta_t > sampling_rate]
                        })
                df_gaps_list.append(row_with_gaps)
                logger.info(f"Analyzing {file.name}: Found {len(row_with_gaps)} rows with delta t > {sampling_rate} ms")
            
            # Find rows with at least one NAN
            nan_df = df[df.eq('NAN').any(axis=1)]
            if len(nan_df) > 0:
                df_nan_list.append(nan_df)

            # Update values for next comparison between consecutive files
            last_row_prev_file = df.iloc[[-1]]
            last_file = file

        except Exception as e:
            logger.error(f"Analyzing {file.name} Error: {e}")

    # Output of the results
    info = meta[0].strip().split('","')
    # Build df
    if df_gaps_list:
        df_gaps = pd.concat(df_gaps_list, ignore_index=True)
        logger.info(f"{'='*60}")
        logger.info(f"TOTAL: {len(df_gaps)} rows with delta t > {sampling_rate} ms (include gaps between files)")
        logger.info(f"{'='*60}\n")
        logger.info(df_gaps)
        # result in a file named time_gaps
        if out_file:
            out_path = input_dir / Path(f'time_gaps_{info[1]}_{info[7][:-1]}.csv')
            df_gaps.to_csv(out_path, index=False)
    else:
        logger.info(f"{'='*60}")
        logger.info("No time gaps found.")
        logger.info(f"{'='*60}\n")
        df_gaps = pd.DataFrame()

    if df_nan_list:
        df_nan = pd.concat(df_nan_list, ignore_index=True)
        logger.info(f"{'='*60}")
        logger.info(f"TOTAL: {len(df_nan)} rows with NAN values")
        logger.info("="*60 + "\n")
        logger.info(df_nan)
        # result in a file named nan_
        if out_file:
            out_path = input_dir / Path(f'nan_{info[1]}_{info[7][:-1]}.csv')
            df_nan.to_csv(out_path, index=False)
    else:
        logger.info(f"{'='*60}")
        logger.info("No NAN values found")
        logger.info(f"{'='*60}\n")
        df_nan = pd.DataFrame()

    return df_gaps, df_nan